linters-settings:
  lll:
    line-length: 165
  funlen:
    lines: 80

linters:
  disable-all: true
  enable:
    - bodyclose
    - errcheck
    - dupl
    - exhaustive
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gosimple
    - govet
    - gosec
    - ineffassign
    - lll
    - misspell
    - nakedret
    - gofumpt
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
service:
  golangci-lint-version: 1.55.2 # use the fixed version to not introduce new linters unexpectedly
  prepare:
    - echo "here I can run custom commands, but no preparation needed for this repo"

run:
  skip-files:
    - path/to/a/file.go