name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Lint
        run: |
          make init
          make lint

      - name: Install dependencies
        run: go get .

      - name: Build
        run: env GOOS=linux GOARCH=amd64 go build

      - name: Test
        run: go test -v ./...

  security-gates:
    uses: Trendyol/security-actions/.github/workflows/security-gates.yml@master
    needs: build
    permissions:
      actions: read
      contents: read
      security-events: write